#!/usr/bin/env python3
"""Build the original-HP seed-stability artifacts (camera-ready support).

Question: are the paper's per-cell (benchmark x backbone) hyperparameter winners
seed-stable, or were the published DINOv3 numbers lucky draws of unstable configs?

Inputs (relative to this directory):
  results/<benchmark>/MiN_<backbone>_seed<seed>.json   paperhp sweep (this study, 90 runs)
  provenance.json                                      per-config HP overrides + qz run ids
  ../results/<benchmark>/MiN_<backbone>_seed<seed>.json  published-stock 120-run sweep (July)

Outputs:
  results/paperhp_cells.csv    long: one row per (benchmark, backbone, seed) with HPs
  docs/paperhp_tables.md       formatted tables + honest-read notes
  docs/fig_paperhp_stability.png  per-cell seed scatter, stock vs paperhp
"""
import csv
import glob
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, 'results')
STOCK_RES = os.path.join(HERE, '..', 'stock_results')
DOCS = os.path.join(HERE, 'docs')
os.makedirs(DOCS, exist_ok=True)

# paper's per-cell avg_acc at qz seed 1993 (best_hyperparameters.csv)
PAPER = {
 ('cifar_100','dinov3_vitb16'): 84.81, ('cifar_100','dinov3_vitl16'): 82.31, ('cifar_100','dinov3_vith16'): 84.35,
 ('cub_200','dinov3_vitb16'): 91.14, ('cub_200','dinov3_vitl16'): 91.66, ('cub_200','dinov3_vith16'): 88.99,
 ('imagenet_a','dinov3_vitb16'): 76.10, ('imagenet_a','dinov3_vitl16'): 82.91, ('imagenet_a','dinov3_vith16'): 64.32,
 ('imagenet_r','dinov3_vitb16'): 88.83, ('imagenet_r','dinov3_vitl16'): 89.92, ('imagenet_r','dinov3_vith16'): 53.71,
 ('omnibenchmark','dinov3_vitb16'): 82.12, ('omnibenchmark','dinov3_vitl16'): 80.42, ('omnibenchmark','dinov3_vith16'): 53.88,
 ('vtab','dinov3_vitb16'): 95.06, ('vtab','dinov3_vitl16'): 95.42, ('vtab','dinov3_vith16'): 95.27,
}
BSHORT = {'dinov3_vitb16': 'v3-B/16', 'dinov3_vitl16': 'v3-L/16', 'dinov3_vith16': 'v3-H/16'}
COLLAPSE_TH = 40.0

prov = json.load(open(os.path.join(HERE, 'provenance.json')))
prov_by_cell = {(v['benchmark'].replace('-', '_').replace('imagenet_r', 'imagenet_r'), v['backbone']): v
                for v in prov.values()}
def cellkey(bm_json, bb):
    return (bm_json, bb)

def load_runs(root):
    out = {}
    for p in glob.glob(os.path.join(root, '*', 'MiN_*_seed*.json')):
        j = json.load(open(p))
        out.setdefault((j['benchmark'], j['backbone']), {})[int(j['seed'])] = j
    return out

paperhp = load_runs(RES)
stock = load_runs(STOCK_RES)

BM_PROV = {'cifar_100': 'cifar-100', 'cub_200': 'cub-200', 'imagenet_a': 'imagenet-a',
           'imagenet_r': 'imagenet-r', 'omnibenchmark': 'omnibenchmark', 'vtab': 'vtab'}

# ---- long CSV ----
rows = []
for (bm, bb), seeds in sorted(paperhp.items()):
    pv = next((v for v in prov.values() if v['benchmark'] == BM_PROV[bm] and v['backbone'] == bb), {})
    ov = pv.get('overrides', {})
    for seed, j in sorted(seeds.items()):
        m = j['metrics']
        rows.append({
            'benchmark': bm, 'backbone': bb, 'backbone_short': BSHORT[bb], 'seed': seed,
            'config': 'paperhp', 'qz_sweep': pv.get('qz_sweep', ''), 'qz_run_id': pv.get('qz_run_id', ''),
            'lr': ov.get('lr'), 'init_lr': ov.get('init_lr', 0.001),
            'gamma': ov.get('gamma'), 'hidden_dim': ov.get('hidden_dim'),
            'batch_size': ov.get('batch_size'), 'init_batch_size': ov.get('init_batch_size'),
            'buffer_batch': ov.get('buffer_batch'),
            'avg_acc': round(100*m['avg_acc'], 2), 'avg_inc_acc': round(100*m['avg_inc_acc'], 2),
            'bwt': round(m['bwt'], 4), 'task0_final': round(100*m['task0_final'], 2),
            'collapsed': 100*m['avg_acc'] < COLLAPSE_TH,
        })
with open(os.path.join(RES, 'paperhp_cells.csv'), 'w', newline='') as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0]))
    w.writeheader()
    w.writerows(rows)

# ---- tables doc ----
def cellstats(seeds):
    v = [100*j['metrics']['avg_acc'] for j in seeds.values()]
    return (st.mean(v), st.stdev(v) if len(v) > 1 else 0.0, min(v), max(v),
            sum(1 for a in v if a < COLLAPSE_TH), len(v))

L = []
L.append('# Original-HP seed-stability — paperhp sweep tables\n')
L.append('Generated by `make_paperhp_tables.py`. Every number is recomputable from')
L.append('`results/paperhp_cells.csv` (this sweep) and `../stock_results/` (published-stock')
L.append('sweep, July 2026). Seeds: 1993, 42, 7, 2024, 31337. Protocol: EASE B0-IncN')
L.append('via the MiN pipeline with seed-shuffled class order. Collapse := avg_acc < 40%.\n')

L.append('## 1. Per-cell verdict: the paper\'s per-cell HP winners across 5 seeds\n')
L.append('| benchmark | backbone | mean ± sd | min..max | collapses | s1993 | paper(qz s1993) | Δ | verdict |')
L.append('|---|---|--:|--:|--:|--:|--:|--:|---|')
for (bm, bb), seeds in sorted(paperhp.items()):
    m, sd, lo, hi, nc, n = cellstats(seeds)
    a93 = 100*seeds[1993]['metrics']['avg_acc']
    pp = PAPER[(bm, bb)]
    d = a93 - pp
    verdict = ('REPRODUCED' if abs(d) <= 3 else 'ROUGH' if abs(d) <= 8 else 'IRREPRODUCIBLE')
    if nc >= 3: verdict = 'IRREPRODUCIBLE (unstable)'
    elif nc >= 1: verdict += ' (lucky-seed)'
    L.append(f'| {bm} | {BSHORT[bb]} | {m:.2f} ± {sd:.2f} | {lo:.1f}..{hi:.1f} | {nc}/{n} | {a93:.2f} | {pp:.2f} | {d:+.2f} | {verdict} |')

L.append('\n**Honest read.** Reproduction at seed 1993 is judged across pipelines: the')
L.append('paper values come from the qz harness, whose imagenet-a/-r test splits (and')
L.append('class-order draw at seed 1993) differ from the MiN pipeline used here — level')
L.append('offsets of a few pp on those benchmarks are expected independent of stability')
L.append('(ina-B: -4.0pp with sd 0.5 is offset, not noise). The sd and collapse columns')
L.append('are pipeline-internal and carry the stability verdict. The cifar-100/v3-B HPs')
L.append('were recovered by run-id hash inversion (no config was recorded anywhere);')
L.append('see ASSUMPTIONS.md #1.\n')

L.append('## 2. Stock (published protocol) vs per-cell winners, same pipeline\n')
L.append('| benchmark | backbone | stock mean ± sd (ncol) | paperhp mean ± sd (ncol) | Δ mean |')
L.append('|---|---|--:|--:|--:|')
for (bm, bb) in sorted(paperhp):
    m1, sd1, _, _, nc1, n1 = cellstats(stock[(bm, bb)])
    m2, sd2, _, _, nc2, n2 = cellstats(paperhp[(bm, bb)])
    L.append(f'| {bm} | {BSHORT[bb]} | {m1:.2f} ± {sd1:.2f} ({nc1}/{n1}) | {m2:.2f} ± {sd2:.2f} ({nc2}/{n2}) | {m2-m1:+.2f} |')
L.append('\n**Honest read.** Same pipeline, same seeds, only the HPs differ — this table')
L.append('is the study\'s core claim. Per-cell tuning eliminates collapse entirely on')
L.append('v3-B (0/30 vs 6/30 stock) and keeps v3-L collapse-free while helping means;')
L.append('on v3-H it fixes exactly one cell (cifar, the only winner with init_lr=1e-4)')
L.append('and leaves 13/30 collapses elsewhere. Selection caveat: the winners were')
L.append('selected on qz seed 1993, one of the 5 seeds reported here; dropping seed 1993')
L.append('changes no verdict (collapse counts are unchanged on the other 4 seeds).\n')

L.append('## 3. Task-0 knobs vs Mode-A collapse (mechanism view)\n')
L.append('| benchmark | backbone | init_lr | init_batch | hidden_dim | lr | collapses |')
L.append('|---|---|--:|--:|--:|--:|--:|')
for (bm, bb), seeds in sorted(paperhp.items()):
    pv = next(v for v in prov.values() if v['benchmark'] == BM_PROV[bm] and v['backbone'] == bb)
    ov = pv['overrides']
    _, _, _, _, nc, n = cellstats(seeds)
    L.append(f"| {bm} | {BSHORT[bb]} | {ov.get('init_lr', 0.001)} | {ov.get('init_batch_size')} | "
             f"{ov.get('hidden_dim')} | {ov.get('lr')} | {nc}/{n} |")
L.append('\n**Honest read.** All 12 collapse-free B/L cells raised init_batch_size to')
L.append('128-512 (stock: 64-128) while keeping init_lr=1e-3; the sole stable H cell')
L.append('lowered init_lr to 1e-4 instead; the 5 unstable H cells kept init_lr=1e-3 at')
L.append('batch 64-96. Consistent with the task-0 blow-up account (LAB_NOTEBOOK,')
L.append('2026-07-30), but this sweep cannot disentangle init_batch_size from')
L.append('hidden_dim/lr covariates — the paused diagnostic ladder would.\n')

with open(os.path.join(DOCS, 'paperhp_tables.md'), 'w') as f:
    f.write('\n'.join(L) + '\n')

# ---- figure ----
try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    cells = sorted(paperhp)
    fig, ax = plt.subplots(figsize=(11, 5.5))
    labels = []
    for i, (bm, bb) in enumerate(cells):
        for src, dx, color in ((stock, -0.16, '#c44'), (paperhp, 0.16, '#2a6')):
            v = [100*j['metrics']['avg_acc'] for j in src[(bm, bb)].values()]
            ax.scatter([i+dx]*len(v), v, s=18, color=color, alpha=0.75, zorder=3)
        pp = PAPER[(bm, bb)]
        ax.plot([i-0.3, i+0.3], [pp, pp], color='k', lw=1.0, ls=':', zorder=2)
        labels.append(f"{bm.replace('_','-')}\n{BSHORT[bb]}")
    ax.axhline(COLLAPSE_TH, color='gray', lw=0.7, ls='--')
    ax.text(len(cells)-0.4, COLLAPSE_TH-3, 'collapse', fontsize=7, color='gray', ha='right')
    ax.set_xticks(range(len(cells)))
    ax.set_xticklabels(labels, fontsize=7)
    ax.set_ylabel('avg_acc (%)')
    ax.set_title('Stock published config (red) vs per-cell paper HPs (green), 5 seeds each; dotted = paper value (qz s1993)')
    ax.set_ylim(0, 100)
    fig.tight_layout()
    fig.savefig(os.path.join(DOCS, 'fig_paperhp_stability.png'), dpi=160)
    print('figure written')
except Exception as e:
    print('figure skipped:', e)

print('wrote results/paperhp_cells.csv and docs/paperhp_tables.md')
